### PR TITLE
#168781794 Setup Eslint to follow airbnb style guide

### PR DESCRIPTION
**Pull request by swaibat**
#### What does this PR do?
- setup Eslint to follow Airbnb style guide
#### Description of Task to be completed?
- setup Eslint
- configure Eslint with Airbnb style guides
-  install Eslint packages in dev-dependences packages include: `Eslint`, `eslint-config-airbnb-base`, `eslint-plugin-import`.
- add new rules in eslint configuration as follows
```
 "root": true,
  "extends": "airbnb-base",
  "env": {
    "node": true,
    "es6": true,
    "mocha": true
  },
  "rules": {
    "one-var": 0,
    "one-var-declaration-per-line": 0,
    "new-cap": 0,
    "consistent-return": 0,
    "no-param-reassign": 0,
    "comma-dangle": 0,
    "curly": ["error", "multi-line"],
    "import/no-unresolved": [2, { commonjs: true }],
    "no-shadow": ["error", { "allow": ["req", "res", "err"] }],
    "valid-jsdoc": ["error", {
      "requireReturn": true,
      "requireReturnType": true,
      "requireParamDescription": false,
      "requireReturnDescription": true
    }],
    "require-jsdoc": ["error", {
        "require": {
            "FunctionDeclaration": true,
            "MethodDefinition": true,
            "ClassDeclaration": true
        }
    }]
  }
}

```
#### How should this be manually tested?
- clone the repo
- run npm i  to install the packages
- write some code to see the style guides
#### Any background context you want to provide?
nan
#### What are the relevant pivotal tracker 

[ #168781794](https://www.pivotaltracker.com/story/show/168781794l)

#### Screenshots (if appropriate)
nan
#### Questions:
nan

### CODE REVIEW

**Review by lemoissonM — APPROVED** [review]

**Review by urbanishimwe — COMMENTED** [review]
I would recommend you to add `.eslintignore` since many dirs doesn't need to be checked
e.g: `migrations`, `seeders`, `models`, `coverage`, `node_modules`, `package-lock.json`, `.nyc-output` etc..

**Review by urbanishimwe — COMMENTED** [review]
recommend you to add `package-lock.json` in .gitignore, if appropriate

**Review by nakiwuge — CHANGES_REQUESTED** [review]
@swaibat good job on the implementation however I would like you to add a rule for `no-console.log` and a rule to `add an empty line at the end of each file`.

**Review by urbanishimwe — COMMENTED** [review]
please also add `"indent": ["error", 2] ` for our indetation to be 2 spaces

**Review by urbanishimwe — CHANGES_REQUESTED** [review]
please also add "indent": ["error", 2] for our indetation to be 2 spaces

**Review by nakiwuge — CHANGES_REQUESTED** [review]
@swaibat Your commit messages have nobody. Please follow the engineering playbook format here . https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions#commit-message

**Review by urbanishimwe — CHANGES_REQUESTED** [review]
`.eslintignore` needs to be `under root dir` not in `src`

**Review by urbanishimwe — APPROVED** [review]

**Review by urbanishimwe — APPROVED** [review]

**Review by urbanishimwe — APPROVED** [review]

**Review by Crispy-rw — APPROVED** [review]

**Review by alexismajya — APPROVED** [review]

**Review by nakiwuge — APPROVED** [review]

**Pull request merged**
